### ISSUE TITLE
RangeError: Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by rtritto** [vikejs/vike-node#10] opened 2024-09-01 09:58 UTC
Using both plugins, `vike/plugin` and `vike-node/plugin` as Vite plugins, I got the "Maximum call stack size exceeded" error.
It works using only one plugin.

[vite.config.ts](https://github.com/rtritto/template-vike-elysia-solid-daisyui/blob/bug-max-call-stack/vite.config.ts)
```ts
import vikeSolid from 'vike-solid/vite'
import { plugin as vike } from 'vike/plugin'
import { vikeNode } from 'vike-node/plugin'

export default {
  // ...
  plugins: [
    vike(),
    vikeSolid(),
    vikeNode('src/server/index.ts')
  ],
  // ...
}
```

## Output
```console
Failed to apply Vite SSR stack trace fix: 52679 |     return;
52680 |   }
52681 |   try {
52682 |     new Function("throw new Error(1)")();
52683 |   } catch (e) {
52684 |     const match = /:(\d+):\d+\)$/.exec(e.stack.split("\n")[1]);
                                               ^
RangeError: Maximum call stack size exceeded.
      at calculateOffsetOnce (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BzOvws4Y.js:52684:40)
      at ssrRewriteStacktrace (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BzOvws4Y.js:52689:3)
      at prepareStackTrace (C:\template-vike-elysia-solid-daisyui\node_modules\vike-node\dist\plugin\plugins\devServerPlugin.js:114:24)
      at calculateOffsetOnce (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BzOvws4Y.js:52684:40)
      at ssrRewriteStacktrace (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BzOvws4Y.js:52689:3)
      at prepareStackTrace (C:\template-vike-elysia-solid-daisyui\node_modules\vike-node\dist\plugin\plugins\devServerPlugin.js:114:24)
      at calculateOffsetOnce (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BzOvws4Y.js:52684:40)
      at ssrRewriteStacktrace (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BzOvws4Y.js:52689:3)
      at prepareStackTrace (C:\template-vike-elysia-solid-daisyui\node_modules\vike-node\dist\plugin\plugins\devServerPlugin.js:114:24)
      at calculateOffsetOnce (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BzOvws4Y.js:52684:40)
```

## Reproduction
1. `git clone https://github.com/rtritto/template-elysia-vike-solid-daisyui.git`
2. `cd template-elysia-vike-solid-daisyui`
3. `git checkout bug-max-call-stack`
4. `yarn`
5. `yarn dev`

**Comment by brillout** [comment] 2024-09-06 08:56
@nitedani It seems related to `vike-node`, ideas? I can take a look at it if you want?

**Comment by rtritto** [comment] 2024-09-06 23:15
Maybe an option for folder of routes should be provided to `vike/plugin` and/or `vike-node/plugin`.

```ts
import vikeSolid from 'vike-solid/vite'
import { plugin as vike } from 'vike/plugin'
import { vikeNode } from 'vike-node/plugin'

export default {
  // ...
  plugins: [
    vike({
      // routes: 'src/pages'  // it should be the default
    }),
    vikeSolid(),
    vikeNode({
      entry: 'src/server/index.ts',
      routes: 'src/api'  // it should be passed to Elysia instance
    })
  ],
  // ...
}
```

**Comment by inetol** [comment] 2024-09-07 11:43
It seems to be related with Bun imports, in my case I had to `external: ['bun']` on vikeNode to be able to build, oddly it only fails on vite dev, in standalone there is no such an issue and everything works correctly.

*server.ts:*
```ts
import { env, serve } from 'bun';
import { Hono } from 'hono';
import vike from 'vike-node/hono';

const port = env.PORT || 3000;
const server = new Hono();

server.use(
    vike()
);

const frontend = serve({
    fetch: server.fetch,
    port: port
});

// ...
```
```console
Failed to apply Vite SSR stack trace fix: 52713 |     return;
52714 |   }
52715 |   try {
52716 |     new Function("throw new Error(1)")();
52717 |   } catch (e) {
52718 |     const match = /:(\d+):\d+\)$/.exec(e.stack.split("\n")[1]);
                                               ^
RangeError: Maximum call stack size exceeded.
      at calculateOffsetOnce (/home/inetol/gitgud/Frontend/node_modules/vite/dist/node/chunks/dep-BaOMuo4I.js:52718:40)
      at ssrRewriteStacktrace (/home/inetol/gitgud/Frontend/node_modules/vite/dist/node/chunks/dep-BaOMuo4I.js:52723:3)
      at prepareStackTrace (/home/inetol/gitgud/Frontend/node_modules/vike-node/dist/plugin/plugins/devServerPlugin.js:114:24)
      at calculateOffsetOnce (/home/inetol/gitgud/Frontend/node_modules/vite/dist/node/chunks/dep-BaOMuo4I.js:52718:40)
      at ssrRewriteStacktrace (/home/inetol/gitgud/Frontend/node_modules/vite/dist/node/chunks/dep-BaOMuo4I.js:52723:3)
      at prepareStackTrace (/home/inetol/gitgud/Frontend/node_modules/vike-node/dist/plugin/plugins/devServerPlugin.js:114:24)
      at calculateOffsetOnce (/home/inetol/gitgud/Frontend/node_modules/vite/dist/node/chunks/dep-BaOMuo4I.js:52718:40)
      at ssrRewriteStacktrace (/home/inetol/gitgud/Frontend/node_modules/vite/dist/node/chunks/dep-BaOMuo4I.js:52723:3)
      at prepareStackTrace (/home/inetol/gitgud/Frontend/node_modules/vike-node/dist/plugin/plugins/devServerPlugin.js:114:24)
      at calculateOffsetOnce (/home/inetol/gitgud/Frontend/node_modules/vite/dist/node/chunks/dep-BaOMuo4I.js:52718:40)

  VITE v5.4.3  ready in 424 ms
  ➜  press h + enter to show help
13 | export default "unknown";
                                           ^
TypeError: undefined is not an object (evaluating '__vite_ssr_import_0__.env.PORT')
      at unknown:13:39
      at processTicksAndRejections (unknown:12:39)

[vite] Server crash: Update a server file or type "r+enter" to restart the server.
```

**Comment by rtritto** [comment] 2024-09-10 22:24
Bun [v1.1.27](https://bun.sh/blog/release-notes/bun-v1.1.27) is out (some improvements and fixes on server).
In the branch, I updated dependencies and added `dev:debug` script.

---

`yarn dev:debug`
```console
Failed to apply Vite SSR stack trace fix: 441 |   var errorString = name + ": " + message;
442 | 
443 |   var state = { nextPosition: null, curPosition: null };
444 |   var processedStack = [];
445 |   for (var i = stack.length - 1; i >= 0; i--) {
446 |     processedStack.push('\n    at ' + wrapCallSite(stack[i], state));
                              ^
RangeError: Maximum call stack size exceeded.
      at prepareStackTrace (C:\template-vike-elysia-solid-daisyui\node_modules\source-map-support\source-map-support.js:446:25)
      at prepareStackTrace (C:\template-vike-elysia-solid-daisyui\node_modules\vike-node\dist\plugin\plugins\devServerPlugin.js:110:91)
      at calculateOffsetOnce (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52718:40)
      at ssrRewriteStacktrace (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52723:3)
      at prepareStackTrace (C:\template-vike-elysia-solid-daisyui\node_modules\vike-node\dist\plugin\plugins\devServerPlugin.js:114:24)
      at calculateOffsetOnce (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52718:40)
      at ssrRewriteStacktrace (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52723:3)
      at prepareStackTrace (C:\template-vike-elysia-solid-daisyui\node_modules\vike-node\dist\plugin\plugins\devServerPlugin.js:114:24)
      at calculateOffsetOnce (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52718:40)
      at ssrRewriteStacktrace (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52723:3)
      at prepareStackTrace (C:\template-vike-elysia-solid-daisyui\node_modules\vike-node\dist\plugin\plugins\devServerPlugin.js:114:24)
      at calculateOffsetOnce (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52718:40)
      at ssrRewriteStacktrace (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52723:3)
      at prepareStackTrace (C:\template-vike-elysia-solid-daisyui\node_modules\vike-node\dist\plugin\plugins\devServerPlugin.js:114:24)
      at calculateOffsetOnce (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52718:40)
      at ssrRewriteStacktrace (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52723:3)
      at prepareStackTrace (C:\template-vike-elysia-solid-daisyui\node_modules\vike-node\dist\plugin\plugins\devServerPlugin.js:114:24)
      at calculateOffsetOnce (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52718:40)
      at ssrRewriteStacktrace (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52723:3)
      at prepareStackTrace (C:\template-vike-elysia-solid-daisyui\node_modules\vike-node\dist\plugin\plugins\devServerPlugin.js:114:24)
      at calculateOffsetOnce (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52718:40)
      at ssrRewriteStacktrace (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52723:3)
      at prepareStackTrace (C:\template-vike-elysia-solid-daisyui\node_modules\vike-node\dist\plugin\plugins\devServerPlugin.js:114:24)
      at calculateOffsetOnce (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52718:40)
      at ssrRewriteStacktrace (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52723:3)
      at prepareStackTrace (C:\template-vike-elysia-solid-daisyui\node_modules\vike-node\dist\plugin\plugins\devServerPlugin.js:114:24)
      at calculateOffsetOnce (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52718:40)
      at ssrRewriteStacktrace (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52723:3)
      at prepareStackTrace (C:\template-vike-elysia-solid-daisyui\node_modules\vike-node\dist\plugin\plugins\devServerPlugin.js:114:24)
      at calculateOffsetOnce (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52718:40)
      at ssrRewriteStacktrace (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52723:3)
      at prepareStackTrace (C:\template-vike-elysia-solid-daisyui\node_modules\vike-node\dist\plugin\plugins\devServerPlugin.js:114:24)

Server running at http://localhost:3000

  VITE v5.4.3
```

---

`yarn dev:debug` with `server` of Bun
```console
Failed to apply Vite SSR stack trace fix: 441 |   var errorString = name + ": " + message;
442 | 
443 |   var state = { nextPosition: null, curPosition: null };
444 |   var processedStack = [];
445 |   for (var i = stack.length - 1; i >= 0; i--) {
446 |     processedStack.push('\n    at ' + wrapCallSite(stack[i], state));
                              ^
RangeError: Maximum call stack size exceeded.
      at prepareStackTrace (C:\template-vike-elysia-solid-daisyui\node_modules\source-map-support\source-map-support.js:446:25)
      at prepareStackTrace (C:\template-vike-elysia-solid-daisyui\node_modules\vike-node\dist\plugin\plugins\devServerPlugin.js:110:91)
      at calculateOffsetOnce (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52718:40)
      at ssrRewriteStacktrace (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52723:3)
      at prepareStackTrace (C:\template-vike-elysia-solid-daisyui\node_modules\vike-node\dist\plugin\plugins\devServerPlugin.js:114:24)
      at calculateOffsetOnce (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52718:40)
      at ssrRewriteStacktrace (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52723:3)
      at prepareStackTrace (C:\template-vike-elysia-solid-daisyui\node_modules\vike-node\dist\plugin\plugins\devServerPlugin.js:114:24)
      at calculateOffsetOnce (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52718:40)
      at ssrRewriteStacktrace (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52723:3)
      at prepareStackTrace (C:\template-vike-elysia-solid-daisyui\node_modules\vike-node\dist\plugin\plugins\devServerPlugin.js:114:24)
      at calculateOffsetOnce (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52718:40)
      at ssrRewriteStacktrace (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52723:3)
      at prepareStackTrace (C:\template-vike-elysia-solid-daisyui\node_modules\vike-node\dist\plugin\plugins\devServerPlugin.js:114:24)
      at calculateOffsetOnce (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52718:40)
      at ssrRewriteStacktrace (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52723:3)
      at prepareStackTrace (C:\template-vike-elysia-solid-daisyui\node_modules\vike-node\dist\plugin\plugins\devServerPlugin.js:114:24)
      at calculateOffsetOnce (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52718:40)
      at ssrRewriteStacktrace (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52723:3)
      at prepareStackTrace (C:\template-vike-elysia-solid-daisyui\node_modules\vike-node\dist\plugin\plugins\devServerPlugin.js:114:24)
      at calculateOffsetOnce (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52718:40)
      at ssrRewriteStacktrace (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52723:3)
      at prepareStackTrace (C:\template-vike-elysia-solid-daisyui\node_modules\vike-node\dist\plugin\plugins\devServerPlugin.js:114:24)
      at calculateOffsetOnce (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52718:40)
      at ssrRewriteStacktrace (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52723:3)
      at prepareStackTrace (C:\template-vike-elysia-solid-daisyui\node_modules\vike-node\dist\plugin\plugins\devServerPlugin.js:114:24)
      at calculateOffsetOnce (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52718:40)
      at ssrRewriteStacktrace (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52723:3)
      at prepareStackTrace (C:\template-vike-elysia-solid-daisyui\node_modules\vike-node\dist\plugin\plugins\devServerPlugin.js:114:24)
      at calculateOffsetOnce (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52718:40)
      at ssrRewriteStacktrace (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52723:3)
      at prepareStackTrace (C:\template-vike-elysia-solid-daisyui\node_modules\vike-node\dist\plugin\plugins\devServerPlugin.js:114:24)

12:22:42 AM [vite] Error when evaluating SSR module C:/workspace/template-vike-elysia-solid-daisyui/src/server/index.ts:
|- TypeError: __vite_ssr_import_2__.serve is not a function. (In '__vite_ssr_import_2__.serve({
  fetch: app.fetch,
  port
})', '__vite_ssr_import_2__.serve' is undefined)
    at <anonymous> (unknown:12:28)
    at processTicksAndRejections (unknown:12:39)

[vite] Server crash: Update a server file or type "r+enter" to restart the server.

  VITE v5.4.3
```

**Comment by brillout** [comment] 2024-09-11 07:45
@rtritto The reproduction https://github.com/rtritto/template-elysia-vike-solid-daisyui is down.

Closing because it seems to be a Bun issue, not a Vike nor `vike-node` one. That said, if there is an easy workaround then we'd be open for a PR.

**Closed by brillout** 2024-09-11 07:45 UTC

**Comment by rtritto** [comment] 2024-09-11 08:11
This is the correct repository: https://github.com/rtritto/template-vike-elysia-solid-daisyui

@brillout @inetol should I open an issue on `vite` or `bun`?

**Comment by rtritto** [comment] 2024-09-11 08:14
So a reproduction without `vike` is needed, anyone can help?
