### ISSUE TITLE
Is vite 6.x supported?

### ISSUE THREAD

**Issue by jasonhilldm** [vikejs/vike-node#23] opened 2024-11-29 04:43 UTC
I am trying to add vike-node to a test project with vike 0.4.205 and vite 6.0.1 and I get a dependency conflict.

```
npm error code ERESOLVE 
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: my-app@0.0.1
npm error Found: vite@6.0.1
npm error node_modules/vite
npm error   dev vite@"^6.0.1" from the root project
npm error   peer vite@">=5.1.0" from vike@0.4.205
npm error   node_modules/vike
npm error     vike@"^0.4.205" from the root project
npm error     peer vike@"^0.4.198" from vike-node@0.2.0
npm error     node_modules/vike-node
npm error       vike-node@"*" from the root project
npm error
npm error Could not resolve dependency:
npm error peer vite@"^5.0.10" from vike-node@0.2.0
npm error node_modules/vike-node
npm error   vike-node@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by magne4000** [comment] 2024-11-29 21:41
Probably yes, I'll take a look this weekend

**Comment by magne4000** [comment] 2024-12-01 12:21
@jasonhilldm should be fixed by `0.2.1`

**Comment by jasonhilldm** [comment] 2024-12-01 19:51
Thanks. I updated to vike-node 0.2.1 and vite 6.0.1 but when I run the test project I get the following error:

`
Error: No known conditions for "./client" specifier in "telefunc" package
`

Do you know if there are breaking changes in vite 6 that require some changes to telefunc setup?

**Comment by brillout** [comment] 2024-12-02 08:49
@jasonhilldm Let me have a look.

**Comment by brillout** [comment] 2024-12-02 09:07
I cannot reproduce. Can you publish a minimal reproduction?

(Closing this as the original seems to be fixed.)

**Closed by brillout** 2024-12-02 09:07 UTC

**Comment by brillout** [comment] 2024-12-02 09:41
Actually I could reproduce. Let me have a look.

**Comment by brillout** [comment] 2024-12-02 12:18
@jasonhilldm https://github.com/vikejs/vike-node/issues/24

**Comment by jasonhilldm** [comment] 2024-12-02 19:16
Thanks!
